import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './providers'
import '@/pages/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nexcent',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
    <html lang="en" className={`${inter.className}`}>
      <body >{children}</body>
      <script src="https://kit.fontawesome.com/333a269518.js"></script>
    </html>
    </Providers>
  )
}
